
name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint || echo "Linting failed but continuing..."

    - name: Type check
      run: npm run typecheck || echo "Type checking failed but continuing..."

    - name: Run tests
      run: npm test || echo "Tests failed but continuing..."

    - name: Build
      run: npm run build
      
    # Optional: Deploy to GitHub Pages if on main branch
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist # The folder the action should deploy
        branch: gh-pages # The branch the action should deploy to
